var coords = [

    { "type": "Feature", "properties": { "Sno": 1, "pdf": "pdf/Screening Sud 2023.pdf#page=15", "photo": "photo/Illustrations_photographiques_pour_le_département_du_Sud_Melon.pdf", "devis": "devis/Devis de Melon.xlsx", "dessin": "dessin/melon_plan.pdf", "notaire": "", "rapport": "", "Nom du site": "Melon", "Latitude": 18.35333, "Longitude": -73.77304, "Arrondissement": "Les Cayes", "Commune": "Maniche", "Section communale": "3eme-Melon", "Code Institution": 715303, "Categorie de l'IS": "CCS" }, "geometry": { "type": "Point", "coordinates": [-73.77304, 18.35333] } },
    { "type": "Feature", "properties": { "Sno": 2, "pdf": "pdf/Screening Sud 2023.pdf#page=30", "photo": "photo/Illustrations_photographiques_pour_le_département_du_Sud_Dory.pdf", "devis": "devis/residence de Dory.xlsx", "dessin": "dessin/Plan_Dory.pdf", "notaire": "notaire/Dory.pdf", "rapport": "", "Nom du site": "Dory", "Latitude": 18.35593, "Longitude": -73.72292, "Arrondissement": "Les Cayes", "Commune": "Maniche", "Section communale": "2ème-Dory", "Code Institution": 715202, "Categorie de l'IS": "CCS" }, "geometry": { "type": "Point", "coordinates": [-73.72292, 18.35593] } },
    { "type": "Feature", "properties": { "Sno": 3, "pdf": "pdf/Screening Sud 2023.pdf#page=25", "photo": "photo/Illustrations_photographiques_pour_le_département_du_Sud__St Louis du Sud.pdf", "devis": "devis/CCS ST Louis du SUD.xlsx", "dessin": "dessin/stlouis_sud_plan.pdf", "notaire": "", "rapport": "", "Nom du site": "St Louis du Sud", "Latitude": 18.26212, "Longitude": -73.54684, "Arrondissement": "Aquin", "Commune": "Saint Louis du Sud", "Section communale": "2ème-Baie-du-Mesle", "Code Institution": 732201, "Categorie de l'IS": "CS" }, "geometry": { "type": "Point", "coordinates": [-73.54684, 18.26212] } },
    { "type": "Feature", "properties": { "Sno": 4, "pdf": "pdf/Screening Sud 2023.pdf#page=61", "photo": "photo/Illustrations_photographiques_pour_le_département_du_Sud__Mne Bernard.pdf", "devis": "devis/centre de sante madame Bernard Ile a vache.xlsx", "dessin": "dessin/Mme BERNARD ( ILE-A-VACHE, SUD)_010646.pdf", "notaire": "", "rapport": "", "Nom du site": "Ile-a-vache", "Latitude": 18.08315, "Longitude": -73.65434, "Arrondissement": "Les Cayes", "Commune": "Ile a Vache", "Section communale": "1ère-Ile-a-Vache", "Code Institution": 716101, "Categorie de l'IS": "CS" }, "geometry": { "type": "Point", "coordinates": [-73.65434, 18.08315] } },
    { "type": "Feature", "properties": { "Sno": 5, "pdf": "pdf/Screening Sud 2023.pdf#page=35", "photo": "photo/Illustrations_photographiques_pour_le_département_Sud__DSS.pdf", "devis": "devis/Devis DSS.xlsx", "dessin": "dessin/DSS (Direction Sanitaire Sud)_034745.pdf", "notaire": "notaire/DDS.pdf", "rapport": "", "Nom du site": "DSS", "Latitude": 18.22027, "Longitude": -73.76555, "Arrondissement": "Les Cayes", "Commune": "Les Cayes", "Section communale": "Bourdet", "Code Institution": null, "Categorie de l'IS": null }, "geometry": { "type": "Point", "coordinates": [-73.76555, 18.22027] } },
    { "type": "Feature", "properties": { "Sno": 6, "pdf": "pdf/Screening Sud 2023.pdf#page=77", "photo": "photo/Illustrations_photographiques_pour_le_département_Sud_Laborde.pdf", "devis": "devis/centre de sante de laborde (SUD).xlsx", "dessin": "dessin/laborde_plan.pdf", "notaire": "", "rapport": "", "Nom du site": "Laborde", "Latitude": 18.28226, "Longitude": -73.80359, "Arrondissement": "Les Cayes", "Commune": "Les Cayes", "Section communale": "3eme-Laborde", "Code Institution": 711309, "Categorie de l'IS": "CCS" }, "geometry": { "type": "Point", "coordinates": [-73.80359, 18.28226] } },
    { "type": "Feature", "properties": { "Sno": 7, "pdf": "pdf/Screening Sud 2023.pdf#page=50", "photo": "photo/Illustrations_photographiques_pour_le_département_du_Sud__St jean du Sud.pdf", "devis": "devis/centre de sante saint jean du Sud.xlsx", "dessin": "", "notaire": "", "rapport": "", "Nom du site": "St Jean du Sud", "Latitude": 18.076123, "Longitude": -73.812615, "Arrondissement": "Port-Salut", "Commune": "Saint Jean", "Section communale": "3eme-Trichet", "Code Institution": 722301, "Categorie de l'IS": "CS" }, "geometry": { "type": "Point", "coordinates": [-73.812615, 18.076123] } },
    { "type": "Feature", "properties": { "Sno": 8, "pdf": "pdf/Screening Sud 2023.pdf#page=40", "photo": "photo/Illustrations_photographiques_pour_le_département_du_Sud__Beraud.pdf", "devis": "devis/Centre de Sante Beraud.xlsx", "dessin": "dessin/RESIDENCE STAFF MEDICALE BERAUD_124758.pdf", "notaire": "notaire/Beraud.pdf", "rapport": "", "Nom du site": "Beraud", "Latitude": 18.20528, "Longitude": -73.8601, "Arrondissement": "Les Cayes", "Commune": "Torbeck", "Section communale": "2ème-Beraud", "Code Institution": 712205, "Categorie de l'IS": "CS" }, "geometry": { "type": "Point", "coordinates": [-73.86, 18.20528] } },
    { "type": "Feature", "properties": { "Sno": 9, "pdf": "pdf/Screening Sud 2023.pdf#page=94", "photo": "photo/Illustrations_photographiques_pour_le_département_du_Sud__Sunligt La colline.pdf", "devis": "devis/CCS Sunlight la coline.xlsx", "dessin": "dessin/sunlight_coline_plan.pdf", "notaire": "notaire/Sunlight.pdf", "rapport": "", "Nom du site": "Sunlight La Colline", "Latitude": 18.30801, "Longitude": -73.24578, "Arrondissement": "Aquin", "Commune": "Aquin", "Section communale": "6ème-La-Colline", "Code Institution": 731602, "Categorie de l'IS": "CS" }, "geometry": { "type": "Point", "coordinates": [-73.24578, 18.30801] } },
    { "type": "Feature", "properties": { "Sno": 10, "pdf": "pdf/Screening Sud 2023.pdf#page=89", "photo": "photo/Illustrations_photographiques_pour_le_département_du_Sud__Charles Pasqua.pdf", "devis": "devis/CCS charles Pasqua.xlsx", "dessin": "dessin/charles_pasqua_plan.pdf", "notaire": "notaire/Charles_pasqua.pdf", "rapport": "", "Nom du site": "Charles Pasqua", "Latitude": 18.29424, "Longitude": -73.34415, "Arrondissement": "Aquin", "Commune": "Aquin", "Section communale": "1ere-Macean", "Code Institution": 731104, "Categorie de l'IS": "CS" }, "geometry": { "type": "Point", "coordinates": [-73.34415, 18.29424] } },
    { "type": "Feature", "properties": { "Sno": 11, "pdf": "pdf/Screening Sud 2023.pdf#page=10", "photo": "photo/Illustrations_photographiques_pour_le_département_du_Sud__Roche a Bateau.pdf", "devis": "devis/Centre de sante Roche a Bateau.xlsx", "dessin": "dessin/roche_bateau_plan.pdf", "notaire": "notaire/Roche a bateau.pdf", "rapport": "", "Nom du site": "Roche-a-Bateau", "Latitude": 18.1786, "Longitude": -73.9966, "Arrondissement": "Coteaux", "Commune": "Coteaux", "Section communale": "5ème-Despas", "Code Institution": 743101, "Categorie de l'IS": "CS" }, "geometry": { "type": "Point", "coordinates": [-73.9966, 18.1786] } },
    { "type": "Feature", "properties": { "Sno": 15, "pdf": "pdf/Screening Sud 2023.pdf#page=20", "photo": "photo/Illustrations_photographiques_pour_le_département_du_Sud__Ferme le blanc.pdf", "devis": "devis/CCS Ferme Le blanc.xlsx", "dessin": "dessin/ferme_leblanc_plan.pdf", "notaire": "", "rapport": "", "Nom du site": "Ferme Leblanc", "Latitude": 18.2881, "Longitude": -73.88374, "Arrondissement": "Cayes", "Commune": "Torbeck", "Section communale": "3eme-Solon", "Code Institution": 712306, "Categorie de l'IS": "CCS" }, "geometry": { "type": "Point", "coordinates": [-73.88374, 18.2881] } },
    { "type": "Feature", "properties": { "Sno": 16, "pdf": "pdf/Screening Sud 2023.pdf#page=83", "photo": "photo/Illustrations_photographiques_pour_le_département_Sud__Guichard.pdf", "devis": "devis/CS GUICHARD.xlsx", "dessin": "dessin/guichard_plan.pdf", "notaire": "", "rapport": "", "Nom du site": "Eben-Ezer de Guichard", "Latitude": 18.29539, "Longitude": -73.82873, "Arrondissement": "Cayes", "Commune": "Camp-Perrin", "Section communale": "1e-Levy-Mersan", "Code Institution": 714103, "Categorie de l'IS": "CCS" }, "geometry": { "type": "Point", "coordinates": [-73.82873, 18.29539] } },
    { "type": "Feature", "properties": { "Sno": 17, "pdf": "pdf/Screening Sud 2023.pdf#page=67", "photo": "photo/Illustrations_photographiques_pour_le_département_du_Sud__Mersan.pdf", "devis": "devis/CS de Mersan.xlsx", "dessin": "dessin/mersan_plan.pdf", "notaire": "notaire/Acte notarié Mersan.pdf", "rapport": "", "Nom du site": "Mersan", "Latitude": 18.281018, "Longitude": -73.843675, "Arrondissement": "Cayes", "Commune": "Camp-Perrin", "Section communale": "1e-Levy-Mersan", "Code Institution": 714104, "Categorie de l'IS": "CCS" }, "geometry": { "type": "Point", "coordinates": [-73.843675, 18.281018] } },
    { "type": "Feature", "properties": { "Sno": 18, "pdf": "pdf/Screening Sud 2023.pdf#page=45", "photo": "photo/Illustrations_photographiques_pour_le_département_du_Sud__Lepretre.pdf", "devis": "devis/centre de Sante le pretre.xlsx", "dessin": "dessin/CENTRE DE SANTE LE PRETRE_034522.pdf", "notaire": "notaire/Lepretre.pdf", "rapport": "", "Nom du site": "Le Prêtre", "Latitude": 18.20604, "Longitude": -73.947338, "Arrondissement": "Cayes", "Commune": "Chantal", "Section communale": "3e Carrefour-Canon", "Code Institution": 713302, "Categorie de l'IS": "CCS" }, "geometry": { "type": "Point", "coordinates": [-73.947338, 18.20604] } },
    { "type": "Feature", "properties": { "Sno": 19, "pdf": "pdf/Screening Sud 2023.pdf#page=5", "photo": "photo/Illustrations_photographiques_pour_le_département_du_Sud__Coteaux.pdf", "devis": "devis/COTEAUX.xlsx", "dessin": "dessin/HCR COTEAUX (SUD)_104617.pdf", "notaire": "notaire/Coteaux.pdf", "rapport": "", "Nom du site": "Coteaux", "Latitude": 18.19662, "Longitude": -74.0309, "Arrondissement": "Cayes", "Commune": "Côteaux", "Section communale": "5ème-Despas", "Code Institution": 741501, "Categorie de l'IS": "CSC" }, "geometry": { "type": "Point", "coordinates": [-74.0309, 18.19662] } },
    { "type": "Feature", "properties": { "Sno": 20, "pdf": "pdf/Screening Sud 2023.pdf#page=72", "photo": "photo/Illustrations_photographiques_pour_le_département_du_Sud__Baie dumesle.pdf", "devis": "devis/CCS baie dumesle.xlsx", "dessin": "dessin/plan_baie_ du_Mesle (SUD)_110217.pdf", "notaire": "notaire/Baie-Dumesle.pdf", "rapport": "", "Nom du site": "Baie du Mesle", "Latitude": 18.22777, "Longitude": -73.61377, "Arrondissement": "Cayes", "Commune": "St Louis du Sud", "Section communale": "2ème-Baie-du-Mesle", "Code Institution": 732206, "Categorie de l'IS": "CS" }, "geometry": { "type": "Point", "coordinates": [-73.54684, 18.26212] } },
    { "type": "Feature", "properties": { "Sno": 21, "pdf": "pdf/Screening Sud 2023.pdf#page=55", "photo": "photo/Illustrations_photographiques_pour_le_département_du_Sud__Sucrerie Henry.pdf", "devis": "devis/centre de sante Sucrerie -Henry.xlsx", "dessin": "dessin/sucrerie_henry_plan.pdf", "notaire": "", "rapport": "", "Nom du site": "Sucrerie-Henry", "Latitude": 18.290833, "Longitude": -73.57027, "Arrondissement": "Aquin", "Commune": "Saint Louis du Sud", "Section communale": "5ème-Sucrerie-Henry", "Code Institution": 732503, "Categorie de l'IS": "CCS" }, "geometry": { "type": "Point", "coordinates": [-73.57027, 18.290833] } },
    { "type": "Feature", "properties": { "Sno": 22, "pdf": "pdf/Screening Nippes 2023 - Prosys.pdf#page=15", "photo": "photo/Illustrations_photographiques_pour_le_département_Nippes__Lhomond.pdf", "devis": "devis/Centre de sante l'homond.xlsx", "dessin": "dessin/LHOMOND (NIPPES)_122635.pdf", "notaire": "notaire/Lohmond.pdf", "rapport": "pdf/Nippes Evaluation finale - Prosys 20 11 2023.pdf#page=17", "Nom du site": "Lhomond", "Latitude": 18.354298, "Longitude": -73.090665, "Arrondissement": "Miragoane", "Commune": "Miragoane", "Section communale": "2eme-Belle-Riviere", "Code Institution": 1011203, "Categorie de l'IS": "CS" }, "geometry": { "type": "Point", "coordinates": [-73.090665, 18.354298] } },
    { "type": "Feature", "properties": { "Sno": 23, "pdf": "pdf/Screening Nippes 2023 - Prosys.pdf#page=8", "photo": "photo/Illustrations_photographiques_pour_le_département_Nippes__Labrousse.pdf", "devis": "devis/centre de sante la brousse.xlsx", "dessin": "", "notaire": "", "rapport": "pdf/Nippes Evaluation finale - Prosys 20 11 2023.pdf#page=9", "Nom du site": "Labrousse", "Latitude": 18.3226, "Longitude": -73.01102, "Arrondissement": "Miragoane", "Commune": "Miragoane", "Section communale": "3eme-Dessources", "Code Institution": 1011305, "Categorie de l'IS": "CS" }, "geometry": { "type": "Point", "coordinates": [-73.01102, 18.3226] } },
    { "type": "Feature", "properties": { "Sno": 24, "pdf": "pdf/Screening Nippes 2023 - Prosys.pdf#page=71", "photo": "photo/Illustrations_photographiques_pour_le_département_Nippes__Lievre.pdf", "devis": "devis/CCS lievre.xlsx", "dessin": "dessin/LIEVRE (NIPPES)_103042.pdf", "notaire": "notaire/Lievre.pdf", "rapport": "pdf/Nippes Evaluation finale - Prosys 20 11 2023.pdf#page=16", "Nom du site": "Lievre", "Latitude": 18.43499, "Longitude": -73.48416, "Arrondissement": "Miragoane", "Commune": "Miragoane", "Section communale": "2ème-section-Belle-rivière", "Code Institution": null, "Categorie de l'IS": "CS" }, "geometry": { "type": "Point", "coordinates": [-73.48416, 18.43499] } },
    { "type": "Feature", "properties": { "Sno": 25, "pdf": "pdf/Screening Nippes 2023 - Prosys.pdf#page=36", "photo": "photo/Illustrations_photographiques_pour_le_département_Nippes___Plaisance.pdf", "devis": "devis/CCS Plaisance du SUD.xlsx", "dessin": "dessin/PLAISANCE (NIPPES)_035158.pdf", "notaire": "", "rapport": "pdf/Nippes Evaluation finale - Prosys 20 11 2023.pdf#page=10", "Nom du site": "Plaisance", "Latitude": 18.43188, "Longitude": -73.590433, "Arrondissement": "Anse-a-Veau", "Commune": "Plaisance", "Section communale": "Centre-Ville", "Code Institution": 1024603, "Categorie de l'IS": "CS" }, "geometry": { "type": "Point", "coordinates": [-73.590433, 18.43188] } },
    { "type": "Feature", "properties": { "Sno": 26, "pdf": "pdf/Screening Nippes 2023 - Prosys.pdf#page=50", "photo": "photo/Illustrations_photographiques_pour_le_département_Nippes__Anse a veau.pdf", "devis": "", "dessin": "", "notaire": "", "rapport": "pdf/Nippes Evaluation finale - Prosys 20 11 2023.pdf#page=11", "Nom du site": "HCR Jules Fleury", "Latitude": 18.482862, "Longitude": -73.289132, "Arrondissement": "Anse-a-Veau", "Commune": "Anse-à-Veau", "Section communale": "Centre-ville", "Code Institution": 1021201, "Categorie de l'IS": "HCR" }, "geometry": { "type": "Point", "coordinates": [-73.289132, 18.482862] } },
    { "type": "Feature", "properties": { "Sno": 27, "pdf": "pdf/Screening Nippes 2023 - Prosys.pdf#page=1", "photo": "photo/Illustrations_photographiques_pour_le_département_des Nippes__Paillant.pdf", "devis": "devis/CCS Paillant.xlsx", "dessin": "", "notaire": "", "rapport": "pdf/Nippes Evaluation finale - Prosys 20 11 2023.pdf#page=8", "Nom du site": "Paillant", "Latitude": 18.4196, "Longitude": -73.14424, "Arrondissement": "Miragoane", "Commune": "Paillant", "Section communale": "6eme-Paillant", "Code Institution": 1014601, "Categorie de l'IS": "CS" }, "geometry": { "type": "Point", "coordinates": [-73.14424, 18.4196] } },
    { "type": "Feature", "properties": { "Sno": 28, "pdf": "pdf/Screening Nippes 2023 - Prosys.pdf#page=57", "photo": "photo/Illustrations_photographiques_pour_le_département_Nippes__DSNI.pdf", "devis": "devis/DSNI.xlsx", "dessin": "dessin/DSNI (NIPPES)_022806.pdf", "notaire": "notaire/DSNI.pdf", "rapport": "pdf/Nippes Evaluation finale - Prosys 20 11 2023.pdf#page=18", "Nom du site": "DSNI", "Latitude": 18.432113, "Longitude": -73.082338, "Arrondissement": "Miragoane", "Commune": "Miragoane", "Section communale": "Centre-ville", "Code Institution": null, "Categorie de l'IS": null }, "geometry": { "type": "Point", "coordinates": [-73.082338, 18.432113] } },
    { "type": "Feature", "properties": { "Sno": 30, "pdf": "pdf/Screening Nippes 2023 - Prosys.pdf#page=78", "photo": "photo/Illustrations_photographiques_pour_le_département_des Nippes__Berquin.pdf", "devis": "devis/CCS berquin.xlsx", "dessin": "dessin/BERQUIN (NIPPES)_022818.pdf", "notaire": "notaire/Berquin.pdf", "rapport": "pdf/Nippes Evaluation finale - Prosys 20 11 2023.pdf#page=15", "Nom du site": "Berquin", "Latitude": 18.43328, "Longitude": -73.061282, "Arrondissement": "Miragoane", "Commune": "Miragoane", "Section communale": "2ème-Belle-rivière", "Code Institution": null, "Categorie de l'IS": "CCS" }, "geometry": { "type": "Point", "coordinates": [-73.061282, 18.43328] } },
    { "type": "Feature", "properties": { "Sno": 31, "pdf": "pdf/Screening Nippes 2023 - Prosys.pdf#page=29", "photo": "photo/Illustrations_photographiques_pour_le_département_Nippes__Arnaud.pdf", "devis": "devis/Centre de Sante Arnaud.xlsx", "dessin": "dessin/ARNAUD (NIPPES)_114815.pdf", "notaire": "notaire/Arnaud.pdf", "rapport": "pdf/Nippes Evaluation finale - Prosys 20 11 2023.pdf#page=13", "Nom du site": "Arnaud", "Latitude": 18.44694, "Longitude": -73.38848, "Arrondissement": "Anse-a-Veau", "Commune": "Arnaud", "Section communale": "Centre-Ville", "Code Institution": 1025301, "Categorie de l'IS": "CS" }, "geometry": { "type": "Point", "coordinates": [-73.38848, 18.44694] } },
    { "type": "Feature", "properties": { "Sno": 33, "pdf": "pdf/Screening Nippes 2023 - Prosys.pdf#page=22", "photo": "photo/Illustrations_photographiques_pour_le_département_du_Sud__Changieux.pdf", "devis": "devis/CCS Changeux.xlsx", "dessin": "dessin/CHANGIEUX (NIPPES)_121119.pdf", "notaire": "notaire/Changeux.pdf", "rapport": "pdf/Nippes Evaluation finale - Prosys 20 11 2023.pdf#page=14", "Nom du site": "Changieux", "Latitude": 18.37273, "Longitude": -73.52812, "Arrondissement": "Anse-a-veau", "Commune": "L'Asile", "Section communale": "2ème-Toumade", "Code Institution": 1022204, "Categorie de l'IS": "CCS" }, "geometry": { "type": "Point", "coordinates": [-73.52812, 18.37273] } },
    { "type": "Feature", "properties": { "Sno": 34, "pdf": "pdf/Screening Nippes 2023 - Prosys.pdf#page=43", "photo": "photo/Illustrations_photographiques_pour_le_département_Nippes__L'asile.pdf", "devis": "devis/Devis Estimatif  l'Asile.xlsx", "dessin": "dessin/HCR L'ASILE  (NIPPES)_040958.pdf", "notaire": "notaire/Acte notarié L'Asile.pdf", "rapport": "pdf/Nippes Evaluation finale - Prosys 20 11 2023.pdf#page=11", "Nom du site": "L'Asile", "Latitude": 18.37991, "Longitude": -73.41844, "Arrondissement": "Anse-a-Veau", "Commune": "L'Asile", "Section communale": "Centre-Ville", "Code Institution": 1022301, "Categorie de l'IS": "HCR" }, "geometry": { "type": "Point", "coordinates": [-73.41844, 18.37991] } },
    { "type": "Feature", "properties": { "Sno": 35, "pdf": "pdf/Screening Nippes 2023 - Prosys.pdf#page=64", "photo": "photo/Illustrations_photographiques_pour_le_département_des Nippes__Grand boucan.pdf", "devis": "devis/centre de sante Gran Boukan.xlsx", "dessin": "dessin/Grand Boucan (NIPPES)_090048.pdf", "notaire": "", "rapport": "pdf/Nippes Evaluation finale - Prosys 20 11 2023.pdf#page=7", "Nom du site": "Grand Boucan", "Latitude": 18.555103, "Longitude": -73.590624, "Arrondissement": "Miragoane", "Commune": "Baradères", "Section communale": "1ère-Grand Boucan", "Code Institution": 1032101, "Categorie de l'IS": "CS" }, "geometry": { "type": "Point", "coordinates": [-73.590624, 18.555103] } },
    { "type": "Feature", "properties": { "Sno": 36, "pdf": "pdf/Screening Grande anse 2023 - Prosys.pdf#page=11", "photo": "photo/Illustrations_photographiques_pour_le_département_Grand'Anse__Moulines.pdf", "devis": "", "dessin": "dessin/MOULINES  (GRAND'ANSE)_024121.pdf", "notaire": "notaire/Acte notarié Moulines.pdf", "rapport": "pdf/Grande anse Evaluation finale - Prosys 20 11 23.pdf#page=7", "Nom du site": "Moulines", "Latitude": 18.47732, "Longitude": -73.99765, "Arrondissement": "Corail", "Commune": "Corail", "Section communale": "1ère-Duquillon", "Code Institution": 831103, "Categorie de l'IS": "CCS" }, "geometry": { "type": "Point", "coordinates": [-73.99765, 18.47732] } },
    { "type": "Feature", "properties": { "Sno": 37, "pdf": "pdf/Screening Grande anse 2023 - Prosys.pdf#page=6", "photo": "photo/Illustrations_photographiques_pour_le_département_Grand Anse__Beaumont.pdf", "devis": "", "dessin": "dessin/HCR BEAUMONT_122056.pdf", "notaire": "", "rapport": "pdf/Grande anse Evaluation finale - Prosys 20 11 23.pdf#page=6", "Nom du site": "CS Sainte Agnès Citimed", "Latitude": 18.47852, "Longitude": -73.94279, "Arrondissement": "Corail", "Commune": "Beaumont", "Section communale": "4ème-Beaumont", "Code Institution": 833401, "Categorie de l'IS": "CS" }, "geometry": { "type": "Point", "coordinates": [-73.94279, 18.47852] } },
    { "type": "Feature", "properties": { "Sno": 38, "pdf": "pdf/Screening Grande anse 2023 - Prosys.pdf#page=1", "photo": "photo/Illustrations_photographiques_pour_le_département_Grand'Anse__Duchity.pdf", "devis": "devis/CCS Duchity.xlsx", "dessin": "dessin/DUCHITY (GRAND'ANSE)_094224.pdf", "notaire": "", "rapport": "pdf/Grande anse Evaluation finale - Prosys 20 11 23.pdf#page=9", "Nom du site": "Duchity", "Latitude": 18.4354321, "Longitude": -73.90503, "Arrondissement": "Corail", "Commune": "Pestel", "Section communale": "5eme-Duchity", "Code Institution": 834503, "Categorie de l'IS": "CCS" }, "geometry": { "type": "Point", "coordinates": [-73.90503, 18.4354321] } },
    { "type": "Feature", "properties": { "Sno": 39, "pdf": "pdf/Screening Grande anse 2023 - Prosys.pdf#page=21", "photo": "photo/Illustrations_photographiques_pour_le_département_Grand 'Anse__Abricots.pdf", "devis": "devis/centre de sante Abricot de pestel.xlsx", "dessin": "dessin/PESTEL ABRICOT_025145.pdf", "notaire": "notaire/Acte notarié Abricot.pdf", "rapport": "pdf/Grande anse Evaluation finale - Prosys 20 11 23.pdf#page=8", "Nom du site": "Centre Espoir Communautaire Abricots de Pestel", "Latitude": 18.498609, "Longitude": -73.773414, "Arrondissement": "Abricot", "Commune": "Abricots", "Section communale": "2ème-Balisiers", "Code Institution": 834207, "Categorie de l'IS": "CCS" }, "geometry": { "type": "Point", "coordinates": [-73.90503, 18.648531] } },
    { "type": "Feature", "properties": { "Sno": 40, "pdf": "pdf/Screening Grande anse 2023 - Prosys.pdf#page=16", "photo": "photo/Illustrations_photographiques_pour_le_département_Grand Anse_numero2.pdf", "devis": "devis/CCS Numero 2.xlsx", "dessin": "dessin/numero2 Centre de sante.pdf", "notaire": "notaire/Numero 2.pdf", "rapport": "pdf/Grande anse Evaluation finale - Prosys 20 11 23.pdf#page=12", "Nom du site": "CCS ND de l’Assomption de Numéro 2", "Latitude": 18.66224, "Longitude": -74.15806, "Arrondissement": "Jeremie", "Commune": "Jeremie", "Section communale": "9ème-Fonds-Rouge-Torberck", "Code Institution": 811908, "Categorie de l'IS": "CCS" }, "geometry": { "type": "Point", "coordinates": [-74.15806, 18.66224] } },
    { "type": "Feature", "properties": { "Sno": 41, "video": "", "pdf": "pdf/Screening Grande anse 2023 - Prosys.pdf#page=26", "photo": "photo/Illustrations_photographiques_pour_le_département_Grand Anse__Leon.pdf", "devis": "devis/Centre de Sante siloe de Leon.xlsx", "dessin": "dessin/LEON_024843.pdf", "notaire": "notaire/Leon.pdf", "rapport": "pdf/Grande anse Evaluation finale - Prosys 20 11 23.pdf#page=11", "Nom du site": " Siloé de Leon", "Latitude": 18.54544, "Longitude": -74.30724, "Arrondissement": "Jeremie", "Commune": "Jeremie", "Section communale": "2ème-Haute-Voldrogue", "Code Institution": 811205, "Categorie de l'IS": "CCS" }, "geometry": { "type": "Point", "coordinates": [-74.30724, 18.54544] } }
]


var points = [
    { "type": "Feature", "properties": { "Sno": 42, "video": "", "pdf": "", "photo": "", "devis": "", "dessin": "", "notaire": "", "rapport": "", "Nom du site": "Roseaux", "Latitude": 18.6003, "Longitude": -74.0157, "Arrondissement": "Roseaux", "Commune": "Roseaux", "Section communale": "", "Code Institution": 832401, "Categorie de l'IS": "Centre de Sante" }, "geometry": { "type": "Point", "coordinates": [-74.0157, 18.6003] } },
    { "type": "Feature", "properties": { "Sno": 43, "video": "", "pdf": "", "photo": "", "devis": "", "dessin": "", "notaire": "", "rapport": "", "Nom du site": "Carrefour Sanon", "Latitude": 18.635694, "Longitude": -74.186441, "Arrondissement": "Jeremie", "Commune": "Jeremie", "Section communale": "", "Code Institution": 811803, "Categorie de l'IS": "Centre de Sante" }, "geometry": { "type": "Point", "coordinates": [-72.40749, 18.5394] } },
    { "type": "Feature", "properties": { "Sno": 44, "video": "", "pdf": "", "photo": "", "devis": "", "dessin": "", "notaire": "", "rapport": "", "Nom du site": "Anse du Clerc", "Latitude": 18.6487, "Longitude": -74.27849, "Arrondissement": "Jeremie", "Commune": "Abricot", "Section communale": "1ere Section Anse du Clerc", "Code Institution": 812102, "Categorie de l'IS": "Centre de Sante" }, "geometry": { "type": "Point", "coordinates": [-74.27849, 18.6487] } },
    { "type": "Feature", "properties": { "Sno": 45, "video": "", "pdf": "", "photo": "", "devis": "", "dessin": "", "notaire": "", "rapport": "", "Nom du site": "Dumont", "Latitude": 18.0518, "Longitude": -73.8803 , "Arrondissement": "Port-Salut", "Commune": "Port-Salut", "Section communale": "", "Code Institution": 721202, "Categorie de l'IS": "Centre de Sante" }, "geometry": { "type": "Point", "coordinates": [-73.8826929, 18.059703] } },
    { "type": "Feature", "properties": { "Sno": 46, "video": "", "pdf": "", "photo": "", "devis": "", "dessin": "", "notaire": "", "rapport": "", "Nom du site": "Arniquet", "Latitude": 18.147495, "Longitude": -73.875842, "Arrondissement": "Port-Salut", "Commune": "Arniquet", "Section communale": "", "Code Institution": 723301, "Categorie de l'IS": "Centre de Sante" }, "geometry": { "type": "Point", "coordinates": [-73.875842, 18.147495] } },
    { "type": "Feature", "properties": { "Sno": 47, "video": "", "pdf": "", "photo": "", "devis": "", "dessin": "", "notaire": "", "rapport": "", "Nom du site": "Ducis", "Latitude": 18.232951, "Longitude": -73.885489, "Arrondissement": "Cayes", "Commune": "Torbeck", "Section communale": "", "Code Institution": 712303, "Categorie de l'IS": "Centre de Sante" }, "geometry": { "type": "Point", "coordinates": [-73.885489, 18.232951] } },
    { "type": "Feature", "properties": { "Sno": 48, "video": "", "pdf": "", "photo": "", "devis": "", "dessin": "", "notaire": "", "rapport": "", "Nom du site": "Javel", "Latitude": 18.418960, "Longitude": -73.267878, "Arrondissement": "Anse a veau", "Commune": "Anse a veau", "Section communale": "", "Code Institution": 1021303, "Categorie de l'IS": "Centre de Sante" }, "geometry": { "type": "Point", "coordinates": [-73.267878, 18.418960] } },
    { "type": "Feature", "properties": { "Sno": 48, "video": "", "pdf": "", "photo": "", "devis": "", "dessin": "", "notaire": "", "rapport": "", "Nom du site": "Petite Rivière", "Latitude": 18.4774, "Longitude": -73.2425, "Arrondissement": "Miragoane", "Commune": "Petite Rivière", "Section communale": "", "Code Institution": 1012103, "Categorie de l'IS": "Centre de Sante" }, "geometry": { "type": "Point", "coordinates": [-73.2425, 18.4774] } }
]




